baseurl = "/"
languageCode = "en-us"
title = "Todds Test"
theme = "hugo-theme-casper"
#disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10
canonifyurls = true

[params]
  description = "this is my description"
  cover = "images/cover.jpg"
  author = "Todd Bowman"
  authorlocation = "Taos, NM"
  authorwebsite = ""
  bio= "my bio"
  logo = "images/logo.png"
  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = "http://feeds.feedburner.com/..."
  githubName = "twbowman"
  twitterName = "twbowman"
  # facebookName = ""
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  [params.social]
    twitter = "your_twitter"
